#!/bin/bash
# /etc/init.d/Pyro4

### BEGIN INIT INFO
# Provides:          Pyro4
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to lauch Pyro4
### END INIT INFO


#Name of the Daemon
DAEMON_NAME=pyro

# Add any command line options for your daemon here
DAEMON_OPTS=""


# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=root

do_pid () {
    ps -ef | grep "Pyro4.naming" | grep -v "grep" | awk '{print $2}'
}

case "$1" in
    start)
	if [ $( do_pid ) ]; then
	PIDFILE=$( do_pid )
	echo "Process is already running at $PIDFILE"
	else
	echo "Starting Pyro4.naming"
        python -m Pyro4.naming | tee /var/log/Pyro4.log &
	PIDFILE=$( do_pid )
	echo "Process running as PID $PIDFILE"
        fi
	;;
    stop)
	PIDFILE=$( do_pid )
	if [ $PIDFILE  ]; then
        echo "Stopping Pyro4"
        kill -9  $PIDFILE
        if [ ! $( do_pid ) ]; then
	echo "Process Pyro4 terminated"
	else
	echo "Process Pyro4 still running"
	fi
	else
	echo "Process not running"
	fi
	;;
    status)
	PIDFILE=$( do_pid )
	if [ $PIDFILE  ]; then
	echo "Process running at PID $PIDFILE"
        else
	echo "Process not running"
	#status_of_proc "$DAEMON_NAME" && exit 0 || exit $?
        fi
	;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|status}"
        exit 1
        ;;
esac

exit 0

